### ISSUE TITLE
Tell us which date it is today directly

### ISSUE THREAD

**Issue by xuew8412** [bentan2013/ScrumSimple#1]
I'd prefer the app can remind me which date it is today automatically when I choosing the date from the calendar.

![image](https://user-images.githubusercontent.com/26732951/33193933-0eea036a-d107-11e7-8299-64dbfc725e75.png)

**Comment by bentan2013** [comment]
Great idea.
I will learn knowledge about this and update it.

**Comment by bentan2013** [comment]
@xuew8412  should fix now
